export type CmsSection = {
  id: number;
  page_slug: string;
  section_key: string;
  section_name: string;
  sort_order: number;
  enabled: boolean;
  eyebrow: string;
  title: string;
  description: string;
  image_url: string;
  button_text: string;
  button_url: string;
  button_bg_color: string;
  button_hover_color: string;
  extra_json: string;
};

export type CmsPage = {
  id: number;
  slug: string;
  name: string;
  route: string;
  enabled: boolean;
  seo_title: string;
  seo_description: string;
  seo_keywords: string;
  canonical_url: string;
  og_title: string;
  og_description: string;
  og_image: string;
  twitter_card: string;
  twitter_title: string;
  twitter_description: string;
  twitter_image: string;
  robots_index: boolean;
  robots_follow: boolean;
  structured_data: string;
  sections: CmsSection[];
};

export type PackageRecord = {
  id: number;
  slug: string;
  title: string;
  short_description: string;
  description: string;
  image_url: string;
  price: string;
  duration: string;
  category: string;
  button_text: string;
  button_url: string;
  button_bg_color: string;
  button_hover_color: string;
  featured: boolean;
  enabled: boolean;
  sort_order: number;
  seo_title: string;
  seo_description: string;
  seo_keywords: string;
  canonical_url: string;
  og_image: string;
  robots_index: boolean;
  robots_follow: boolean;
  structured_data: string;
};

export type BlogPost = {
  id: number;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  tags: string;
  featured_image: string;
  author_name: string;
  published_at: string;
  featured: boolean;
  enabled: boolean;
  sort_order: number;
  seo_title: string;
  seo_description: string;
  seo_keywords: string;
  canonical_url: string;
  og_title: string;
  og_description: string;
  og_image: string;
  twitter_title: string;
  twitter_description: string;
  twitter_image: string;
  robots_index: boolean;
  robots_follow: boolean;
  structured_data: string;
};

export type ContentRecord = {
  id: number;
  collection_key: string;
  slug: string;
  title: string;
  subtitle: string;
  content: string;
  image_url: string;
  icon_url: string;
  link_text: string;
  link_url: string;
  social_facebook: string;
  social_x: string;
  social_youtube: string;
  enabled: boolean;
  sort_order: number;
};

export type ContactSubmission = {
  id: number;
  name: string;
  email: string;
  phone: string;
  subject: string;
  message: string;
  source_page: string;
  status: "unread" | "read" | "replied";
  admin_note: string;
  created_at: string;
};

export type NavItem = {
  id: string;
  label: string;
  url: string;
  enabled: boolean;
  children: NavItem[];
};

export type SiteSettings = {
  site_name: string;
  logo_url: string;
  favicon_url: string;
  default_og_image: string;
  default_meta_title: string;
  default_meta_description: string;
  topbar_email: string;
  topbar_phone: string;
  topbar_address: string;
  sunrise_text: string;
  sunset_text: string;
  cta_text: string;
  cta_url: string;
  nav_items: NavItem[];
  social_links: Record<string, string>;
  imagebb_api_key: string;
  footer_logo_url: string;
  footer_background_url: string;
  footer_description: string;
  footer_newsletter_title: string;
  footer_newsletter_description: string;
  footer_email_placeholder: string;
  footer_button_text: string;
  footer_copyright: string;
  footer_shape_1_url: string;
  footer_shape_2_url: string;
  footer_shape_3_url: string;
  footer_shape_4_url: string;
  contact_form_title: string;
  contact_info_title: string;
  contact_info_description: string;
  contact_button_text: string;
  contact_success_message: string;
  contact_name_placeholder: string;
  contact_email_placeholder: string;
  contact_phone_placeholder: string;
  contact_subject_placeholder: string;
  contact_message_placeholder: string;
  contact_phone_secondary: string;
  contact_email_secondary: string;
};

export type PublicSiteSettings = Omit<SiteSettings, "imagebb_api_key">;
