"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import type { ContentRecord } from "../lib/cms-db";

export default function ScholarsClient({ items, showHeading = false, showAllButton = false }: { items: ContentRecord[]; showHeading?: boolean; showAllButton?: boolean }) {
  return <section className="islamic_scholars section-padding"><div className="container">{showHeading && <div className="row"><div className="col-lg-12"><motion.div className="section-heading text-center mb-30" initial={{ opacity: 0, y: -50 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><span data-cms-eyebrow>Knowledgeable Guidance</span><h2 data-cms-title>Meet Our Islamic Scholars</h2><img src="/assets/img/icons/title.svg" alt="Title Icon" /></motion.div></div></div>}<div className="row g-4">{items.map((item, index) => { const url = item.link_url || `/instructor-details/${item.slug}`; return <div key={item.id} className="col-xl-3 col-md-6 col-12"><motion.div className="single-scholar" initial={{ opacity: 0, y: 80 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: .8, delay: index * .1 }} viewport={{ once: true }}><div className="scholar_img position-relative"><Link href={url}><img src={item.image_url || "/assets/img/scholars/1.png"} alt={item.title} /></Link><ul className="scholar_social">{item.social_facebook && <li><a href={item.social_facebook}><i className="fa-brands fa-facebook-f"></i></a></li>}{item.social_x && <li><a href={item.social_x}><i className="fa-brands fa-x-twitter"></i></a></li>}{item.social_youtube && <li><a href={item.social_youtube}><i className="fa-brands fa-youtube"></i></a></li>}</ul></div><h3><Link href={url}>{item.title}</Link></h3><p>{item.subtitle}</p></motion.div></div>; })}{showAllButton && <div className="col-12 text-center mt-5"><Link href="/instructors" className="green_btn" data-cms-button="true"><span>View All Scholars</span></Link></div>}</div></div></section>;
}
