import type { SiteSettings } from "../lib/cms-db";

export const headerDefaults: SiteSettings = {
  site_name: "Hajj Agency",
  logo_url: "/assets/img/logo.svg",
  favicon_url: "",
  default_og_image: "",
  default_meta_title: "Hajj and Umrah Agency",
  default_meta_description: "Trusted Hajj and Umrah packages, guidance and travel support.",
  topbar_email: "support@example.com",
  topbar_phone: "+998524 522 655",
  topbar_address: "3500 Lenox Road, USA",
  sunrise_text: "Sunrise At: 5.30 AM",
  sunset_text: "Sunset At: 5.30 PM",
  cta_text: "Join Now",
  cta_url: "/register",
  nav_items: [
    { id: "home", label: "Home", url: "/", enabled: true, children: [] },
    { id: "about", label: "About", url: "/about", enabled: true, children: [] },
    { id: "packages", label: "Packages", url: "/packages", enabled: true, children: [] },
    { id: "blog", label: "Blog", url: "/blog", enabled: true, children: [] },
    { id: "contact", label: "Contact", url: "/contact", enabled: true, children: [] },
  ],
  social_links: {},
  imagebb_api_key: "",
  footer_logo_url: "/assets/img/logo-white.svg",
  footer_background_url: "/assets/img/bg/overlay.svg",
  footer_description: "<p>Trusted Hajj and Umrah packages, guidance and travel support.</p>",
  footer_newsletter_title: "Latest Newsletter",
  footer_newsletter_description: "<p>Subscribe and receive our Hajj and Umrah offers and updates.</p>",
  footer_email_placeholder: "Enter Email Address",
  footer_button_text: "Subscribe Now",
  footer_copyright: "Copyright 2026 All Rights Reserved Hajj Agency",
  footer_shape_1_url: "/assets/img/shapes/fstars.svg",
  footer_shape_2_url: "/assets/img/shapes/fdots.svg",
  footer_shape_3_url: "/assets/img/shapes/fcircle.svg",
  footer_shape_4_url: "/assets/img/shapes/vline.svg",
  contact_form_title: "Get In Touch",
  contact_info_title: "Contact Information",
  contact_info_description: "<p>Feel free to reach out to us with any questions about Hajj and Umrah.</p>",
  contact_button_text: "Send Message",
  contact_success_message: "Thank you. Your message has been sent to our team.",
  contact_name_placeholder: "Your Name",
  contact_email_placeholder: "Your Email",
  contact_phone_placeholder: "Your Phone",
  contact_subject_placeholder: "Subject",
  contact_message_placeholder: "Your Message",
  contact_phone_secondary: "",
  contact_email_secondary: "",
};
